// <auto-generated />
using System;
using CopilotStudioTestRunner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CopilotStudioTestRunner.Data.Migrations
{
    [DbContext(typeof(TestRunnerDbContext))]
    [Migration("20260221183952_AddJudgeSettingToTestSuite")]
    partial class AddJudgeSettingToTestSuite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DirectLineBackoffSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectLineBotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DirectLineMaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DirectLineReplyTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectLineSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DirectLineUseWebChannelSecret")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DirectLineUseWebSocket")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JudgeApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JudgeEndpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JudgeMaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JudgeModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("JudgePassThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("JudgeTemperature")
                        .HasColumnType("REAL");

                    b.Property<double>("JudgeTopP")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionGenApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionGenEndpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionGenModel")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<double?>("EndChapter")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartChapter")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Chunks");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.GlobalQuestionGenerationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<double>("TopP")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GlobalQuestionGenerationSettings");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.JudgeSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FactualityWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("HelpfulnessWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("IntentMatchWeight")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PassThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SafetyWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("TaskSuccessWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<double>("TopP")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseReferenceAnswer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("JudgeSettings");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FactualityScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("HelpfulnessScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("IntentMatchScore")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("JudgeCitations")
                        .HasColumnType("TEXT");

                    b.Property<string>("JudgeRationale")
                        .HasColumnType("TEXT");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OverallScore")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SafetyScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("TaskSuccessScore")
                        .HasColumnType("REAL");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("TestCaseId");

                    b.HasIndex("RunId", "TestCaseId")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageLatencyMs")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionUser")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitSha")
                        .HasColumnType("TEXT");

                    b.Property<double>("MedianLatencyMs")
                        .HasColumnType("REAL");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("TEXT");

                    b.Property<double>("P95LatencyMs")
                        .HasColumnType("REAL");

                    b.Property<int>("PassedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptVersion")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SuiteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTestCases")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("SuiteId");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptanceCriteria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ExpectedEntities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedIntent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceAnswer")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SuiteId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("UserInput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("SuiteId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.TestCaseDocument", b =>
                {
                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TestCaseId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("TestCaseDocuments");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("JudgeSettingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JudgeSettingId");

                    b.ToTable("TestSuites");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.TestSuiteAgent", b =>
                {
                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TestSuiteId", "AgentId");

                    b.HasIndex("AgentId");

                    b.ToTable("TestSuiteAgents");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.TranscriptMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawActivityJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("TranscriptMessages");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.Chunk", b =>
                {
                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.Result", b =>
                {
                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.Run", "Run")
                        .WithMany("Results")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.TestCase", "TestCase")
                        .WithMany("Results")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Run");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.Run", b =>
                {
                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.Agent", "Agent")
                        .WithMany("Runs")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.TestSuite", "Suite")
                        .WithMany("Runs")
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.Document", "SourceDocument")
                        .WithMany("GeneratedTestCases")
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.TestSuite", "Suite")
                        .WithMany("TestCases")
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceDocument");

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.TestCaseDocument", b =>
                {
                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.Document", "Document")
                        .WithMany("TestCaseDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.TestCase", "TestCase")
                        .WithMany("TestCaseDocuments")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.TestSuite", b =>
                {
                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.JudgeSetting", "JudgeSetting")
                        .WithMany()
                        .HasForeignKey("JudgeSettingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JudgeSetting");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.TestSuiteAgent", b =>
                {
                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.Agent", "Agent")
                        .WithMany("TestSuiteAgents")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.TestSuite", "TestSuite")
                        .WithMany("TestSuiteAgents")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.TranscriptMessage", b =>
                {
                    b.HasOne("CopilotStudioTestRunner.Domain.Entities.Result", "Result")
                        .WithMany("TranscriptMessages")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("TestSuiteAgents");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.Document", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("GeneratedTestCases");

                    b.Navigation("TestCaseDocuments");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.Result", b =>
                {
                    b.Navigation("TranscriptMessages");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.Run", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.TestCase", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("TestCaseDocuments");
                });

            modelBuilder.Entity("CopilotStudioTestRunner.Domain.Entities.TestSuite", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("TestCases");

                    b.Navigation("TestSuiteAgents");
                });
#pragma warning restore 612, 618
        }
    }
}
